name: Docker

permissions: read-all

on:
  push:
    branches:
      - master
      - develop
    tags:
    - v[0-9]+.[0-9]+.[0-9]+**
  pull_request:
    branches:
    - master
    - develop

jobs:

  release:
    if: ${{ startsWith(github.ref, 'refs/tags/v') || (github.event_name == 'pull_request') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
      with:
        egress-policy: audit
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Get branch name
      id: get-branch-name
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          HEADREF="${{ github.head_ref }}"
          EVENT_BASEREF=""
        else
          HEADREF="${GITHUB_REF##*/}"
          EVENT_BASEREF="${GITHUB_EVENT_BASE_REF#refs/heads/}"
        fi
        
        FINAL_BRANCHNAME="${EVENT_BASEREF:-$HEADREF}"
        
        # Export to GitHub Actions
        echo "branch=$FINAL_BRANCHNAME" >> $GITHUB_ENV
      env:
        GITHUB_EVENT_BASE_REF: ${{ github.event.base_ref }}
      shell: bash

    - name: Parse version
      uses: nowsprinting/check-version-format-action@bb1181a02ee5d9ae4feead2842236183c85152c6 # v4.0.7
      id: version
      with:
        prefix: 'v'

    - name: Report invalid version
      if: ${{ startsWith(github.ref, 'refs/tags/v') && steps.version.outputs.is_valid != 'true' }}
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      with:
        script: |
            core.setFailed('Tag name "${{ github.ref_name }}" is not a valid semantic version!')

    - name: Set up JDK 22
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
      with:
        distribution: 'temurin'
        java-version: 22

    - name: Cache Local Maven Repo
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        path: ~/.m2/repository
        key: release-maven-${{ hashFiles('pom.xml') }}

    - uses: s4u/maven-settings-action@894661b3ddae382f1ae8edbeab60987e08cf0788 # v4.0.0
      with:
        servers: |
          [{"id": "mii", "username": "${{ github.actor }}", "password": "${{ secrets.GITHUB_TOKEN }}"},{"id": "bzkf", "username": "${{ github.actor }}", "password": "${{ secrets.GITHUB_TOKEN }}"}]

    - name: Prepare Docker Repository
      id: repo
      run: |
        echo ::set-output name=repository::$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')

    - name: Maven Package
      run: mvn -Pdownload-ontology -B -DskipTests package

    - name: Login to GitHub Docker Registry
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

    - name: Build and push Docker image
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        tags: |
          ${{ startsWith(github.ref, 'refs/tags/v') &&
          format('ghcr.io/{0}:{1}',
          steps.repo.outputs.repository,
          steps.version.outputs.full_without_prefix) ||
          '' }}
          ${{ startsWith(github.ref, 'refs/tags/v') &&
          steps.version.outputs.is_stable == 'true' &&
          format('ghcr.io/{0}:latest',
          steps.repo.outputs.repository) ||
          '' }}
          ${{ github.event_name == 'pull_request' &&
          format('ghcr.io/{0}:pr-{1}',
          steps.repo.outputs.repository,
          github.event.pull_request.number) ||
          ''}}
        push: true
